spring:

  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 0924
    driver-class-name: com.mysql.cj.jdbc.Driver  # 确保有这一行
logging:
  pattern:
    dateformat: yyyy年MM月dd日 HH:mm:ss.SSS
server:
  port: 8081