spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 0924
    driver-class-name: com.mysql.cj.jdbc.Driver  # 确保有这一行
  data:
    redis:
      host: localhost
      port: 6379
      #password: 0924
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 3000ms

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: FallenLeavesMall_JwtSecret_#@abc123_zhly_666  # 最少32位
  expiration: 1800  # 过期时间(秒) - 30分钟
  refresh-expiration: 7200  # 刷新令牌过期时间 - 2小时
  issuer: FallenLeavesMall  # 签发人
auth:
  max-sessions-per-user: 5  # 每个用户最多登录设备数
  enable-token-rotation: true  # 启用令牌轮换
#日志
logging:
  pattern:
    dateformat: yyyy年MM月dd日 HH:mm:ss.SSS
server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8