spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 0924
  data:
    redis:
      host: localhost
      port: 6379
      #password: 0924
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 3000ms

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: FallenLeavesMall_JwtSecret_#@abc123_zhly_666  # 最少32位
  expiration: 7200  # 过期时间(秒)
  refresh-expiration: 604800  # 刷新令牌过期时间(7天)
  issuer: FallenLeavesMall  # 签发人